[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
graphql = { path = "../graphql" }

tokio = { version = "1.8", features = ["full"] }
poem = "1.0.13"
async-graphql = "2.10.8"
async-graphql-poem = "2.10.8"
log = "0.4.14"
serde_json = "1.0.68"
slab = "0.4.5"
dotenv = "*"
anyhow = "1.0.45"
sqlx = { version = "0.5.9", features = ["postgres", "offline"] }
pretty_env_logger = "0.4.0"
uuid = "0.8.2"
thiserror = "1.0.30"
pwhash = "1.0.0"

