[package]
name = "graphql"
version = "0.0.1"
edition = "2021"
publish = false

[lib]
name = "graphql"
path = "src/lib.rs"

[dependencies]
async-graphql = { version = "2.10.8", features = ["uuid", "chrono"] }
chrono = "0.4.19"
db = { path = "../db" }
serde = "1.0.130"
serde_json = "1.0.69"
sqlx = { version = "0.5.9", features = ["postgres"] }
uuid = "0.8.2"
