[package]
name = "graphql"
version = "0.0.1"
edition = "2021"
publish = false

[lib]
name = "graphql"
path = "src/lib.rs"

[dependencies]
async-graphql = { version = "2.10.8", features = ["uuid"] }
db = { path = "../db" }
sqlx = { version = "0.5.9", features = ["postgres"] }
uuid = "0.8.2"
