[package]
name = "scrapers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
db = { path = "../db" }
csv = "1.2.2"
reqwest = { version = "0.11.18" }
thirtyfour = "0.31.0"
tokio = { version = "1.30.0", features = ["full"] }
sqlx = { version = "0.7", features = ["postgres", "macros"] }
tracing = "0.1.39"
serde_json = "1.0.111"
